### PR TITLE
Omnipay 3 update

### PR DESCRIPTION
**Pull request by Lewiatan**
Hello

I prepared an update for your gateway to make it compatible with Omnipay 3. I migrated all requests to PayU SDK since for some reason I had issues with authenticating over REST API, but in the end I think it looks much cleaner. I didn't make any updates to notification functionality since I'm not familiar with that, but I see you didn't use http client there, so all should be good.

Best regards

### CODE REVIEW

**Comment by northys** [comment]
@Lewiatan have you tried it in your project? Sadly, we are locked at old omnipay version so I cannot test your changes.

But I'm willing to mergne your PR and release v1.0.0 so you can use it. This is not a problem :)

**Comment by northys** [comment]
And of course - thanks for the PR!

**Comment by Lewiatan** [comment]
Hey,

I tried it in my project, as well as I tried your test files with omnipay 3. I didn't test notifications since I'm still at early development stage and I don't have public IP for my project yet.

If you're stuck with older version and if the release would be just for me, then I can use it from my repo, no problem. I guess you don't want to be bothered with issues for v3 or so :D But if you still would like to release, I can offer my help with issues if needed :)

Also if you don't mind, I can publish my fork as a gateway for version 3 (of course with visible notation that it's just the fork and with the credits to you) so in case of issues I'd handle those directly. 

I'll leave the decision to you :) 

And you're welcome, I'm happy that I could contribute :)

**Comment by northys** [comment]
Hi,

I've merged your request and created tag v1.0.0. If you are going to push more PRs to this repository we are willing to give you a merge access so you can manage the v3 master branch. Btw there are no open issues now and its on people who use it to solve it. That's open source. Once we will be also forced to upgrade to omnipay v3 :)

Development of version v0.x is in branch v0 since now cc @jspetrak

**Comment by Lewiatan** [comment]
Hi,

thanks :) for now I'm not planning further upgrades since it's all I need :) 

If you need anything just tag me and I'll do my best to help :)

**Pull request merged**
